
name: Run Linter for every commit
on:
  push: {}
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - run: |-
        gem install rubocop rubocop-rails
        rubocop
